### ISSUE TITLE
iperf3

### ISSUE THREAD

**Issue by pjebs** [moutten/docker-iperf#1]
Is this running iperf3?

**Comment by moutten** [comment]
This is currently _not_ running iperf3. I wasn't able to get iperf3 to install on Alpine Linux the last time I was working on this.

**Comment by moutten** [comment]
@pjebs I did create a docker image on docker hub for iperf3, although it's a little larger than this iperf image.

https://github.com/moutten/docker-iperf/tree/3.0

It's building as a tag from docker hub.

`docker run -d -p 5201:5201 moutten/iperf:3.0`

**Comment by pjebs** [comment]
Did you encounter difficulties with alpine linux and hence switch to debian?

**Comment by moutten** [comment]
@pjebs It wouldn't compile. I have not had a chance to try iperf version 3.1 though.

**Comment by pjebs** [comment]
I actually tried your image but it seems old.
I'm really only interested in the `iperf3 --server --one-off` option but it doesn't seem to work: https://github.com/esnet/iperf/issues/363

**Comment by moutten** [comment]
It appears that a feature only supported by iperf 3.1 not 3.0. I just pushed up another tag which has version 3.1. Try this.

`docker run --rm -p 5201:5201 moutten/iperf:3.1 --server --one-off`

**Comment by pjebs** [comment]
Thank you so much.

**Comment by pjebs** [comment]
I'm trying to build iperf3.1 on alpine (for a docker container). Do you have any suggestions on how it could be done?

**Comment by moutten** [comment]
I wish I did. I'm just not familiar enough with Alpine to be of much help.

**Comment by pjebs** [comment]
Hi @moutten 
I've been using your docker code for iPerf3.1 for a while now.
I was wondering what I must do to change it to get the latest version of 3.1 since it's been updated.
I'm perplexed by how you event got these urls:

```
ADD https://iperf.fr/download/iperf_3.1/libiperf0_3.1.2-1_amd64.deb /libiperf0_3.1.2-1_amd64.deb
ADD https://iperf.fr/download/iperf_3.1/iperf3_3.1.2-1_amd64.deb /iperf3_3.1.2-1_amd64.deb
RUN dpkg -i /libiperf0_3.1.2-1_amd64.deb /iperf3_3.1.2-1_amd64.deb && \
    rm /libiperf0_3.1.2-1_amd64.deb /iperf3_3.1.2-1_amd64.deb
```

**Comment by moutten** [comment]
This is where I found those packages:

https://iperf.fr/iperf-download.php#ubuntu

Are you trying to build an image with a newer version than 3.1.2?

**Comment by pjebs** [comment]
I've noticed that more updates have been committed. Presumably less bugs. Maybe there are no formal updates on that website but definitely stuff is happening on github.

**Comment by bkmeneguello** [comment]
iPerf 3.1 on alpine:
https://github.com/bkmeneguello/docker-iperf

**Comment by pjebs** [comment]
@bkmeneguello How'd you get it to work?

**Comment by bkmeneguello** [comment]
By using a glibc port to alpine (non sense, I know, but works very well)

**Comment by ghost** [comment]
https://pkgs.alpinelinux.org/package/edge/main/x86/iperf3 exists now.

**Comment by ghost** [comment]
...Yeah, that doesn't exist in x86_64 for unknown reasons.

So I did it the hard way

![](https://media.giphy.com/media/KscoZccAOBgCk/giphy.gif)

https://github.com/baxterworks-build/docker-iperf3-build

**Comment by moutten** [comment]
Thanks for the heads up @voltagex, I used the alpine edge version on docker hub to grab the alpine package. This works for me. https://github.com/moutten/docker-iperf/tree/3.1

**Comment by moutten** [comment]
You can test it out by using my image from docker hub.

```
docker run -d -p 5201:5201 moutten/iperf:3.1
```

**Comment by ghost** [comment]
Sigh, of course there was an easier way. Thanks @moutten!
